### ISSUE TITLE
DiscountServiceImpl.getOrderEntryDiscountAmount throws NullPointerException

### ISSUE THREAD

**Issue by tttodorov13** [nemesis-software/nemesis-support#14] opened 2017-05-30 13:26 UTC
If there is persisted non empty cart for logged user the cart can not be displayed.
Attachments:
1. Screenshot of database product with price;
2. Screenshot of IDEA debugger catching the exception;
3. Error stack-trace.

![database](https://cloud.githubusercontent.com/assets/4050441/26585268/43679434-4554-11e7-8e09-9dcd9b09b4b7.png)
![error](https://cloud.githubusercontent.com/assets/4050441/26585267/43666f32-4554-11e7-8993-4c5a14768d89.png)
[error.txt](https://github.com/nemesis-software/nemesis-support/files/1038443/error.txt)

**Comment by vasilb751** [comment] 2017-07-06 14:24
Hello Toshko,

we couldn't reproduce your issue. It is not a normal situation to have an entry in a cart without base price ( how this product was added to the cart ? ).

It would be easier if you provide a step-by-step flow or better a JUnit test.

Regards,
Vasil

**Comment by gochev** [comment] 2017-08-22 08:02
Closing since no additional information provided and marking it as unable to reproduce.

**Closed as completed by gochev** 2017-08-22 08:02 UTC
