### ISSUE TITLE
Enum search property

### ISSUE THREAD

**Issue by vdoychev** [nemesis-software/nemesis-support#18] opened 2017-08-18 11:18 UTC
1)
I need to use annotation for enum field to show in console default search. 

@MixIn({ CustomerEntityDefinition.class })
public interface VivacomCustomerEntityDefinition extends CustomerEntityDefinition {

    String NAME = "vivacom_customer";

    @Column(name = "customer_segment")
    @Enumerated(EnumType.STRING)
    @SearchProperty(name = "Customer Segment", weight = 2)
    @EntityProperty(name = "Customer Segment", weight = 2, section = @EntitySection(name = "Vivacom"))
    SegmentTypeDefinition getCustomerSegment();

    void setCustomerSegment(SegmentTypeDefinition customerSegment);

and result is "Override in child!"

2)
When I try to write custom search, I import "filter-enum-field". If I try to override value property, the result is "Override in child!". And if I don't override it, the result is "Cannot read property 'indexOf' of undefined at FilterEnumField.render"
     
 <FilterEnumField readOnly={false} onFilterChange={this.onFilterChange.bind(this)} filterItem={{
				name : 'status',
				fieldLabel : 'Status',
			}} />

Do i need to make somewhere else changes and where ot get values ?

**Comment by TeodorTunev** [comment] 2017-08-18 11:33
Hello, the values of Enum field should be passed as properties of filterItem
Example: 
filterItem={{
name : 'status',
fieldLabel : 'Status',
**values: ['test1', 'test2', 'test3']**
}} />

**Comment by TeodorTunev** [comment] 2017-08-18 11:39
About the first question i have checked it and if filter field response says its **xtype: "nemesisEnumField"**, it works properly.

**Comment by gochev** [comment] 2017-08-18 11:44
I can confirm the search on enum works. 

We do have search on enum on the payment transaction but also I have added on on the order just for test both works as expected.

Something is wrong with the definition of the enum perhaps ? In anyway this is a custom implementation issue and not a bug in the console so closing it.

Test with payment transaction there are 2 enums there.

![screen shot 2017-08-18 at 14 42 44](https://user-images.githubusercontent.com/5537142/29457604-a1d82c32-8423-11e7-83ff-70d839bb19c2.jpg)


For future bugs please fallow the rules on https://github.com/nemesis-software/nemesis-support **README**.

_Each issue should be submited with detailed information in order to be fixed. This information includes:_

_Steps to reproduce from start.nemesis.io generated project, including the version you are using.
Unit test showing the the issue, and showing the expected behaviour._

**Closed as completed by gochev** 2017-08-18 11:44 UTC
