### ISSUE TITLE
Issue with backend console Vivacom

### ISSUE THREAD

**Issue by MHSF** [nemesis-software/nemesis-support#11] opened 2017-05-23 14:16 UTC
Then the backend console is open with the following parameters in the properties file:
````
#
# nemesis Platform - NExt-generation Multichannel E-commerce SYStem
#
# Copyright (c) 2010 - 2016 nemesis
# All rights reserved.
#
# This software is the confidential and proprietary information of nemesis
# ("Confidential Information"). You shall not disclose such Confidential
# Information and shall use it only in accordance with the terms of the
# license agreement you entered into with nemesis.
#
server.port=8080
server.contextPath=/backend
console.restBaseUrl=https://vivacom2.scalefocus.com/rest/
console.websiteBaseUrl=https://vivacom2.scalefocus.com/
````
And the console is behind nginx proxy with the following configuration:
````
server {
        listen   443 ssl;
        keepalive_timeout   70;

        root /var/www/;
        server_name vivacom2.scalefocus.com;

        # SSL
        ssl_protocols           TLSv1.1 TLSv1.2;
        ssl_ciphers             AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5:+HIGH;
        ssl_certificate         /etc/nginx/cert/cert.pem;
        ssl_certificate_key     /etc/nginx/cert/key.pem;
        ssl_session_cache       shared:SSL:20m;
        ssl_session_timeout     20m;


        location /backend/ {
                proxy_set_header X-Real-IP  $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto  https;
                add_header X-Proxy-Cache $upstream_cache_status;
                proxy_pass http://10.0.0.126:8080;
                proxy_read_timeout 300s;
        }
}
````
We can successfully log in the backend console, but we can see only blank page without anything on it. From the developement tolls f12 on the browser we can see that the following components are not loaded:
````
https://vivacom2.scalefocus.com/backend/resources/bundle.js
https://vivacom2.scalefocus.com/backend/resources/styles.css
````
When we log on backend servers and try to get them localy the result is:
````
curl http://localhost:8080/backend/resources/bundle.js
{"timestamp":1495541574626,"status":500,"error":"Internal Server Error","exception":"java.io.FileNotFoundException","message":"Jar URL cannot be resolved to absolute file path because it does not reside in the file system: war:file:/opt/nemesis-console.war*/resources/bundle.js","path":"/backend/resources/bundle.js"}You have new mail in /var/spool/mail/root
The backend is started by systemd service with the following ExecStart command:
ExecStart=/bin/sh -c '/opt/jdk1.8.0_121/bin/java -jar /opt/nemesis-console.war 2>&1 > /opt/backend-springboot.log'
````
But you can simply test it with:
````
java -jar nemesis-console.war
`````
Where the nemesis-console.war is produced by `mvn clean package`.

Please check why the js and the css cannot be loaded.

**Comment by ptahchiev** [comment] 2017-05-26 06:38
Hello Velislav,

here's the gist of what I run: https://gist.github.com/ptahchiev/77f8f77f1f806b262c79c52ace38e4d1

And here's a screenshot of the console working fine for me:

![console](https://cloud.githubusercontent.com/assets/5320045/26483679/f06e7ce4-41f6-11e7-8e4a-ed855a61b540.png)

Perhaps you are using an old version. Try to pull the latest release - it works on port 8443 now with HTTPS.

**Comment by gochev** [comment] 2017-05-26 11:26
The problem is not the HTTPS or the version.
His problem is when he starts the console with java -jar instead of mvn spring-boot:run it doesn't work as expected.

**Comment by ptahchiev** [comment] 2017-05-26 11:50
Again - it works for me (look at my gist). From what I can tell:
````
https://vivacom2.scalefocus.com/backend/resources/bundle.js
https://vivacom2.scalefocus.com/backend/resources/styles.css
````
He is accessing the console over nginx - it could be misconfiguration of nginx.

**Comment by ptahchiev** [comment] 2017-05-29 10:43
Hello Velislav,

the latest commit in master allows you to specify locations for static resources in `application.properties` file. The `application.properties` file now contains the following:
````
spring.resources.staticLocations=/resources/
````
which will run fine if you are running it with the spring-boot maven plugin. If you want to run it a jar, then you need to change the property to:

````
spring.resources.staticLocations=classpath:/resources/
````

Let me know if it works.

**Comment by gochev** [comment] 2017-08-22 08:04
Closing it since no information is provided by the partner in the issue, but I was informed by mail it works.

**Closed as completed by gochev** 2017-08-22 08:04 UTC
